name: Parse SSM parameter

on:
  push

jobs:
  get-ssm-env:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: aws-ssm-to-env
        uses: eliasjcjunior/aws-ssm-parameters-action@main
        with:
          paths: '/env/EXPORO_SERVICE_AUTH
